FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /build
COPY . .
RUN mvn -q package -pl backend/notification-service -am -DskipTests

FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=build /build/backend/notification-service/target/*.jar /app/notification-service.jar
EXPOSE 8085 9093
ENTRYPOINT ["java", "-jar", "/app/notification-service.jar"]
